In [12]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

# don't use ndarray to create ndarrays!


print(x[0])
print(x[4], end='\n')

print('\n')
      
print(x[-1])
print(x[-2])

1
5


5
4


In [17]:
x[4] = 20

print(x)

[ 1  2  3  4 20]


In [18]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(y[0, 0])  
print(y[0, 2])
print(y[2, 2])

y[2, 2] = 20
print(y)

1
3
20
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 20]]


## Deleting elements in an ndarray ##

Note, I'm not sure how you delete from both axis. 

Also, I'm not sure how you would delete individual values

In [24]:
x = np.array([1, 2, 3, 4, 5])
x = np.delete(x, [0, 4])
print(x)

[2 3 4]


In [29]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

# delete the first row (which is 'axis=0')
Y = np.delete(x, 0, axis=0)
print('\n', Y)

# delete the first and first columns
Y = np.delete(x, [0, 1], axis=1)
print('\n', Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[3]
 [6]
 [9]]


## Appending to a 2D array ##

Note, you can't append a row after appending a column!

In [45]:
x = np.array([1, 2, 3, 4])
x = np.append(x, 100)
print(x)

y = np.append(x, [101, 102, 103])
print(y)



[  1   2   3   4 100]
[  1   2   3   4 100 101 102 103]


In [46]:
# append rows and columns to a 2D array
a = np.arange(1, 10).reshape(3, 3)
print(a)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

append_col = np.append(matrix, [[10], [11], [12]], axis=1)  
print('\n', append_col)

# CAN'T DO THIS
append_row = np.append(append_col, [[0], [0], [0], [0]], axis=0)
print('\n', append_row)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

## Insterting elements into ndarrays ##

You can create a first order array using np.array([ ... ]) or np.arange(1, 10)

You can create a second order array using np.array([[1, 2, 3, 4],[5, 6, 7, 8]]) or np.arange(1, 9).reshape(2, 4) -MAKE SURE TO INCLUDE THE HARD BRACKETS + THE ROW BRACKETS!!

Note - you CAN insert a column into a 2D array after inserting a row!



In [58]:
x = np.array([1, 2, 3, 4, 5])
print(x)

#insert at the specified position
y = np.insert(x, 3, [7, 7, 7])
print('\n', y)

[1 2 3 4 5]

 [1 2 3 7 7 7 4 5]


In [62]:
x = np.array([[1, 2, 3], [7, 8, 9]])
print(x)

# '2' is the position here
x = np.insert(x, 2, [10, 11, 12], axis =0)
print('\n', x)

x = np.insert(x, 1, 5, axis=1)
print('\n', x)

[[1 2 3]
 [7 8 9]]

 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]

 [[ 1  5  2  3]
 [ 7  5  8  9]
 [10  5 11 12]]


## Stacking numpy arrays ##

In [67]:
x = np.array([1, 2, 3])

y = np.array([[4, 5, 6], [7, 8, 9]])

# stack 1 first order with a second order vertically using vstack
z = np.vstack((x, y))
print('\n', z)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
x = np.array([1, 2, 3])
print('\n', x)

y = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('\n', y)

# stack 1 first order with a second order vertically using vstack
x = x.reshape(3, 1)
print('\n', x)

z = np.hstack((y, x))
print('\n', z)


 [1 2 3]

 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [[1]
 [2]
 [3]]

 [[ 4  5  6  1]
 [ 7  8  9  2]
 [10 11 12  3]]


## Slicing ##

start is included, end is excluded

ndarray[start:end]          # x[0:4] means indexes 0, 1, 2, 3

ndarray[start:]

ndarray[:end]

Slicing only creates a view of the array. It does not make a new array

### So, if you make changes in the view you also make changes in the original!!! ###

Need to use the z = np.copy(ndarray)



In [88]:
x = np.arange(1, 21).reshape(4, 5)
print('\n', x)

y = x[1:4, 2:5]
print('\n', y)

z = x[1:, 2:]
print('\n', z)

z = x[:3, 2:]
print('\n', z)

# grab all the rows 
z = x[:, 2:]
print('\n', z)

# grab one column - now makes it into a first order array
z = x[:, 2:3]
print('\n', z)  



 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]

 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 3]
 [ 8]
 [13]
 [18]]


In [90]:
# change a value in the view, which changes the original
z[3, 0] = 555
print('\n', z)  

print('\n', x)



 [[  3]
 [  8]
 [ 13]
 [555]]

 [[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17 555  19  20]]


In [96]:
# use copy to avoid this
x = np.arange(1, 21).reshape(4, 5)
print('\n', x)  

z = np.copy(x[1:, 2:])
print('\n', z)  

# alternative
z = x[0:, 2:].copy()
print('\n', z)  

# show that x hasn't changed
print('\n', x)  


 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Use numpy arrays to select indices ##

the argument is the specific rows or columns to select

In [99]:
rows = np.array([1, 2, 3])

z = x[rows, :].copy()
print('\n', z)



 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [104]:
print('\n', x)

# extract the diagonal
z = np.diag(x)
print('\n', z)

z = np.diag(x, k=1)
print('\n', z)


 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [ 1  7 13 19]

 [ 2  8 14 20]


## Find all the unique values ##

In [106]:
x = np.array([[1, 2, 3], [2, 3, 3], [4, 5, 6]])
y = np.unique(x)
print('\n', y)


 [1 2 3 4 5 6]
