## Boolean indexing, Set Operations, Sorting ##

In [50]:
import numpy as np

x = np.arange(25)
print('\n', x)

x = x.reshape(5, 5)
print('\n', x)

# use a boolean to filter the results
x = x[(x>10) & (x<20)]  
print('\n', x)

x = x.reshape(3, 3)
print('\n', x)

x[((x>13) & (x<17))] = 0
print('\n', x)


 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 [11 12 13 14 15 16 17 18 19]

 [[11 12 13]
 [14 15 16]
 [17 18 19]]

 [[11 12 13]
 [ 0  0  0]
 [17 18 19]]


In [51]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([6, 7, 8, 9, 10])

# set ops on a one dimensional array
print(np.intersect1d(x, y))

# x minus y
print(np.setdiff1d(x, y))

# removes dups
print(np.union1d(x, y))



[6]
[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]


## Sort ##

Can be as a function (np.sort()) - sorts the array out of place and doesn't change the original array

Can be as a method (x.sort()) - sorts the array in place, and changes the original array

Here is sorting a 1D array:

In [52]:
x = np.random.randint(1, 11, size=(10,))
print('\n', x)  

y = np.unique(x)
print('\n', y)

y = np.sort(y)
print('\n', y)

print('\n', x)

x.sort()
print('\n', x)  




 [8 5 6 8 4 1 6 6 4 8]

 [1 4 5 6 8]

 [1 4 5 6 8]

 [8 5 6 8 4 1 6 6 4 8]

 [1 4 4 5 6 6 6 8 8 8]


Here is sorting a 2D array

In [53]:
# make a random 2D array
x = np.random.randint(1, 11, size=(5, 5))
print('\n', x)

# now sort by rows (which kind of seems like sorting by columns)
y = np.sort(x, axis=0)
print('\n', y)  



 [[ 6  1  8  3  7]
 [ 3  5  9  2  9]
 [ 6  1  6  1  5]
 [ 4  1  9 10  7]
 [ 8  4  1  4  9]]

 [[ 3  1  1  1  5]
 [ 4  1  6  2  7]
 [ 6  1  8  3  7]
 [ 6  4  9  4  9]
 [ 8  5  9 10  9]]


## Arithmetic ops and Broadcasting ##

arrays need to have the same shape or be broadcastable

In [91]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# this adds each index together
print(x + y)
print(np.add(x, y))

# subtract
print(x - y)
print(np.subtract(x, y))

# multiply
print(x * y)
print(np.multiply(x, y))

# divide
print(x / y)
print(np.divide(x, y))

# try it with a 2D array
x = np.array([[1, 2], [3, 4]])
print('\n', x)
y = np.array([[5, 6], [7, 8]])
print('\n', y)

# this adds each index position together
print('\n', x + y)

# perform arithmetic ops on the whole array
print('\n', np.sqrt(x))

# exponential, where 'e' equals approx 2.718 
print('\n', np.exp(x))

# power
print('\n', np.power(x, 2))

# average
print('\n', np.mean(x))



[ 6  8 10 12]
[ 6  8 10 12]
[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]

 [[1 2]
 [3 4]]

 [[5 6]
 [7 8]]

 [[ 6  8]
 [10 12]]

 [[1.         1.41421356]
 [1.73205081 2.        ]]

 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

 [[ 1  4]
 [ 9 16]]

 2.5


In [77]:
# average of a row - use the method on the nparray
print('\n', x)
print('\n', x.mean(axis=0))
print('\n', x.mean(axis=1))

# sum
print('\n', x.sum(axis=0))

# maximum
print('\n', x.max(axis=0))

# add/multiply a number to all values of the array
# broadcasts the number along the array
print('\n', x + 10)
print('\n', x * 10)

# broacast a 1D array to a 2D array. Need to ensure the smaller array can be expanded to fit the shape of the larger array
y = np.array([5, 5])
print('\n', x + y)


 [[1 2]
 [3 4]]

 [2. 3.]

 [1.5 3.5]

 [4 6]

 [3 4]

 [[11 12]
 [13 14]]

 [[10 20]
 [30 40]]

 [[6 7]
 [8 9]]


## Broadcasting something over the whole array ##

Interesting ways to change the shape of an array from 1D to 2D

In [90]:
# 1d array
x = np.array([10, 100, 1000])
print('\n', x)

# 2D array - notice the double brackets
y = x.reshape(3, 1)
print('\n', y)

z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('\n', z)

# this will add x to each row of z
print('\nThis adds the array to every row of the 2D array')
print('\n', x + z)

# this will add y to each column of z
print('\nThis adds the array to every column of the 2D array')
print('\n', y + z)


 [  10  100 1000]

 [[  10]
 [ 100]
 [1000]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This adds the array to every row of the 2D array

 [[  11  102 1003]
 [  14  105 1006]
 [  17  108 1009]]

This adds the array to every column of the 2D array

 [[  11   12   13]
 [ 104  105  106]
 [1007 1008 1009]]


In [85]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
